export const data = [
    {   id:1,
        imgURL:"https://skatlab.com/assets/images/games/my-100-first-words.jpg",
        ridirectURL:"https://skatlab.com/game/my-first-100-words",
        name:"My First 100 Words",
        iframe:"https://play.gamepix.com/my-100-first-words/embed"
    },
    {   id:2,
        imgURL:"https://skatlab.com/assets/images/games/cerkio.jpg",
        ridirectURL:"https://skatlab.com/game/cerkio",
        name:"Cerkio",
        iframe:"https://play.gamepix.com/cerkio/embed",
    }, 
    {   id:3,
        imgURL:	"https://skatlab.com/assets/images/games/flamit.jpg",
        ridirectURL:"https://skatlab.com/game/flamit",
        name:"Flamit",
        iframe:"https://play.gamepix.com/flamit/embed"
    },
    {   id:4,
        imgURL:"https://skatlab.com/assets/images/games/stickman-street-fighting.jpg",
        ridirectURL:"https://skatlab.com/game/stickman-street-fighting-3D",
        name:"Stickman Street Fighting 3D",
        iframe:"https://play.gamepix.com/stickman-street-fighting/embed"
    },
    {   id:5,
        imgURL:"https://skatlab.com/assets/images/games/stickman-street-fighting.jpg",
        ridirectURL:"https://skatlab.com/game/merge-mine-idle-clicker",
        name:"Merge Mine - Idle Clicker",
        iframe:"https://play.gamepix.com/merge-mine-idle-clicker/embed"
    },
    {   id:6,
        imgURL:"https://skatlab.com/assets/images/games/sokoballs.jpg",
        ridirectURL:"https://skatlab.com/game/sokoballs",
        name:"Sokoballs",
        iframe:"https://play.gamepix.com/sokoballs/embed"
    },
    {   id:7,
        imgURL:"https://skatlab.com/assets/images/games/body-drop-3d.jpg",
        ridirectURL:"https://skatlab.com/game/body-drop-3D",
        name:"Body Drop 3D",
        iframe:"https://play.gamepix.com/body-drop-3d/embed"
    },
    {   id:8,
        imgURL:"https://skatlab.com/assets/images/games/penalty-kick-wiz.jpg",
        ridirectURL:"https://skatlab.com/game/penalty-kick-wiz",
        name:"Penalty Kick Wiz",
        iframe:"https://play.gamepix.com/penalty-kick-wiz/embed"
    },
    {   id:9,
        imgURL:"https://skatlab.com/assets/images/games/penalty-kick-wiz.jpg",
        ridirectURL:"https://skatlab.com/game/kobadoo-shapes",
        name:"Kobadoo Shapes",
        iframe:"https://play.gamepix.com/kobadoo-shapes/embed"
    },
    {   id:10,
        imgURL:"https://skatlab.com/assets/images/games/turbo-dismounting.jpg",
        ridirectURL:"https://skatlab.com/game/turbo-dismounting",
        name:"Turbo Dismounting",
        iframe:"https://play.gamepix.com/turbo-dismounting/embed"
    },
    {   id:11,
        imgURL:"https://skatlab.com/assets/images/games/robot-band-find-the-differences.jpg",
        ridirectURL:"https://skatlab.com/game/robot-band-find-the-differences",
        name:"Robot Band - Find the differences",
        iframe:"https://play.gamepix.com/robot-band-find-the-differences/embed"
    },
    {   id:12,
        imgURL:"https://skatlab.com/assets/images/games/barbies-sketch.jpg",
        ridirectURL:"https://skatlab.com/game/barbies-sketch",
        name:"Barbies Sketch",
        iframe:"https://play.gamepix.com/barbies-sketch/embed"
    },
    {   id:13,
        imgURL:"https://skatlab.com/assets/images/games/stickman-warriors-1.jpg",
        ridirectURL:"https://skatlab.com/game/stickman_warriors",
        name:"Stickman Warriors",
        iframe:"https://play.gamepix.com/stickman-warriors-1/embed"
    },
    {   id:14,
        imgURL:"https://skatlab.com/assets/images/games/royal-couple-halloween-party.jpg",
        ridirectURL:"https://skatlab.com/game/royal_couple_halloween_party",
        name:"Royal Couple Halloween Party",
        iframe:"https://play.gamepix.com/royal-couple-halloween-party/embed"
    },
    {   id:15,
        imgURL:"https://skatlab.com/assets/images/games/morphit.jpg",
        ridirectURL:"https://skatlab.com/game/morphit",
        name:"Morphit",
        iframe:"https://play.gamepix.com/morphit/embed"
    },
    {   id:16,
        imgURL:"https://skatlab.com/assets/images/games/yummy-toast.jpg",
        ridirectURL:"https://skatlab.com/game/yummy_toast",
        name:"Yummy Toast",
        iframe:"https://play.gamepix.com/yummy-toast/embed"
    },
    {   id:17,
        imgURL:"https://skatlab.com/assets/images/games/parmesan-partisan.jpg",
        ridirectURL:"https://skatlab.com/game/parmesan_partisan",
        name:"Parmesan Partisan",
        iframe:"https://play.gamepix.com/parmesan-partisan/embed"
    }, 
    {   id:18,
        imgURL:"	https://skatlab.com/assets/images/games/kobadoo-emojis.jpg",
        ridirectURL:"https://skatlab.com/game/kobadoo_emojis",
        name:"Kobadoo Emojis",
        iframe:"https://play.gamepix.com/kobadoo-emojis/embed"
    },  
    {   id:19,
        imgURL:"https://skatlab.com/assets/images/games/gelatino.jpg",
        ridirectURL:"https://skatlab.com/game/gelatino",
        name:"Gelatino",
        iframe:"https://play.gamepix.com/gelatino/embed"
    },  
    {   id:20,
        imgURL:"https://skatlab.com/assets/images/games/hoops-and-fruits.jpg",
        ridirectURL:"https://skatlab.com/game/hoops_fruits",
        name:"Hoops & Fruits",
        iframe:"https://play.gamepix.com/hoops-and-fruits/embed"
    },  
    {   id:21,
        imgURL:"https://skatlab.com/assets/images/games/dotto-botto.jpg",
        ridirectURL:"https://skatlab.com/game/dotto_botto",
        name:"Dotto Botto",
        iframe:"https://play.gamepix.com/dotto-botto/embed"
    },  
    {   id:22,
        imgURL:"https://skatlab.com/assets/images/games/galactic-pixel-storm.jpg",
        ridirectURL:"https://skatlab.com/game/galactic_pixel_storm",
        name:"Galactic Pixel Storm",
        iframe:"https://play.gamepix.com/galactic-pixel-storm/embed"
    },  
    {   id:23,
        imgURL:"https://skatlab.com/assets/images/games/going-right.jpg",
        ridirectURL:"https://skatlab.com/game/going_right",
        name:"Going Right",
        iframe:"https://play.gamepix.com/going-right/embed"
    },  
    {   id:24,
        imgURL:"https://skatlab.com/assets/images/games/adrenaline-rush-miami-drive.png",
        ridirectURL:"https://skatlab.com/game/adrenaline-rush-miami-drive",
        name:"Adrenaline Rush - Miami Drive",
        iframe:"https://play.gamepix.com/adrenaline-rush-miami-drive/embed"
    },  
    {   id:25,
        imgURL:"https://skatlab.com/assets/images/games/words-blocks-puzzle.jpg",
        ridirectURL:"https://skatlab.com/game/words-blocks-puzzle",
        name:"Words Blocks - Puzzle",
        iframe:"https://play.gamepix.com/words-blocks-puzzle/embed"
    },
    {   id:26,
        imgURL:"https://skatlab.com/assets/images/games/rail-rush-pro.jpg",
        ridirectURL:"https://skatlab.com/game/rail-rush-pro",
        name:"Rail Rush Pro",
        iframe:"https://play.gamepix.com/rail-rush-pro/embed"
    },
    {   id:27,
        imgURL:"https://skatlab.com/assets/images/games/solitaire-farm-seasons.jpg",
        ridirectURL:"https://skatlab.com/game/solitaire-farm-seasons",
        name:"Solitaire Farm: Seasons",
        iframe:"https://play.gamepix.com/solitaire-farm-seasons/embed"
    }, 
    {   id:28,
        imgURL:"https://skatlab.com/assets/images/games/flying-shodow.jpg",
        ridirectURL:"https://skatlab.com/game/flying-shodow",
        name:"Flying Shodow",
        iframe:"https://play.gamepix.com/flying-shodow/embed"
    },
    {   id:29,
        imgURL:"https://skatlab.com/assets/images/games/tic-tac-toe-quiz.jpg",
        ridirectURL:"https://skatlab.com/game/tic-tac-toe-quiz",
        name:"Tic Tac Toe Quiz",
        iframe:"https://play.gamepix.com/tic-tac-toe-quiz/embed"
    },
    {   id:30,
        imgURL:"https://skatlab.com/assets/images/games/clouds-and-sheep-2.jpg",
        ridirectURL:"https://skatlab.com/game/clouds-and-sheep-2",
        name:"Clouds and Sheep 2",
        iframe:"https://play.gamepix.com/clouds-and-sheep-2/embed"
    },
    {   id:31,
        imgURL:"https://skatlab.com/assets/images/games/ado-stunt-cars-3.jpg",
        ridirectURL:"https://skatlab.com/game/ado-stunt-cars-3",
        name:"Ado Stunt Cars 3",
        iframe:"https://play.gamepix.com/ado-stunt-cars-3/embed"
    },
    {   id:32,
        imgURL:"https://skatlab.com/assets/images/games/wooden-block-jigsaw-puzzle.jpg",
        ridirectURL:"https://skatlab.com/game/wooden-block-jigsaw-puzzle",
        name:"Wooden Block Jigsaw Puzzle",
        iframe:"https://play.gamepix.com/wooden-block-jigsaw-puzzle/embed"
    },
    {   id:33,
        imgURL:"https://skatlab.com/assets/images/games/mahjong-tiles-matching.jpg",
        ridirectURL:"https://skatlab.com/game/mahjong-tiles-matching",
        name:"Mahjong Tiles Matching",
        iframe:"https://play.gamepix.com/mahjong-tiles-matching/embed"
    },
    {   id:34,
        imgURL:"https://skatlab.com/assets/images/games/ludo-brawl.jpg",
        ridirectURL:"https://skatlab.com/game/ludo-brawl",
        name:"Ludo Brawl",
        iframe:"https://play.gamepix.com/ludo-brawl/embed"
    },
    {   id:35,
        imgURL:"https://skatlab.com/assets/images/games/shell-shockers.jpg",
        ridirectURL:"https://skatlab.com/game/shell-shockers",
        name:"Shell Shockers",
        iframe:"https://play.gamepix.com/shell-shockers/embed"
    },
    {   id:36,
        imgURL:"https://skatlab.com/assets/images/games/yummy-tales.jpg",
        ridirectURL:"https://skatlab.com/game/yummy-tales",
        name:"Yummy Tales",
        iframe:"https://play.gamepix.com/yummy-tales/embed"
    },
    {   id:37,
        imgURL:"https://skatlab.com/assets/images/games/kobadoo-numbers.jpg",
        ridirectURL:"https://skatlab.com/game/kobadoo-numbers",
        name:"Kobadoo Numbers",
        iframe:"https://play.gamepix.com/kobadoo-numbers/embed"
    },
    {   id:38,
        imgURL:"https://skatlab.com/assets/images/games/kiba-and-kumba-tri-towers-solitaire.jpg",
        ridirectURL:"https://skatlab.com/game/kiba-and-kumba-tri-towers-solitaire",
        name:"Kiba & Kumba: Tri-Towers Solitaire",
        iframe:"https://play.gamepix.com/kiba-and-kumba-tri-towers-solitaire/embed"
    },
    {   id:39,
        imgURL:"https://skatlab.com/assets/images/games/cut-the-rope-2.jpg",
        ridirectURL:"https://skatlab.com/game/cut-the-rope-2",
        name:"Cut the Rope 2",
        iframe:"https://play.gamepix.com/cut-the-rope-2/embed"
    },  
    {   id:40,
        imgURL:"https://skatlab.com/assets/images/games/mahjong-story.jpg",
        ridirectURL:"https://skatlab.com/game/mahjong-story",
        name:"Mahjong Story",
        iframe:"https://play.gamepix.com/mahjong-story/embed"
    },
    {   id:41,
        imgURL:"https://skatlab.com/assets/images/games/moto-x3m.jpg",
        ridirectURL:"https://skatlab.com/game/moto-x3m",
        name:"Moto X3M",
        iframe:"https://play.gamepix.com/moto-x3m/embed"
    },
    {   id:42,
        imgURL:"https://skatlab.com/assets/images/games/4-colors-pgs.jpg",
        ridirectURL:"https://skatlab.com/game/4-colors-pgs",
        name:"4 Colors Pgs",
        iframe:"https://play.gamepix.com/4-colors-pgs/embed"
    }, 
    {   id:43,
        imgURL:"https://skatlab.com/assets/images/games/copa-toon.jpg",
        ridirectURL:"https://skatlab.com/game/copa-toon",
        name:"Toon Cup",
        iframe:"https://play.gamepix.com/copa-toon/embed"
    },  
    {   id:44,
        imgURL:"https://skatlab.com/assets/images/games/cut-the-rope.jpg",
        ridirectURL:"https://skatlab.com/game/cut-the-rope",
        name:"Cut The Rope",
        iframe:"https://play.gamepix.com/cut-the-rope/embed"
    },  
    {   id:45,
        imgURL:"https://skatlab.com/assets/images/games/checkers-classic.jpg",
        ridirectURL:"https://skatlab.com/game/checkers-classic",
        name:"Checkers Classic",
        iframe:"https://play.gamepix.com/checkers-classic/embed"
    },  
    {   id:46,
        imgURL:"https://skatlab.com/assets/images/games/tic-tac-toe-the-original-game.jpg",
        ridirectURL:"https://skatlab.com/game/tic-tac-toe-the-original-game",
        name:"Tic Tac Toe The Original Game",
        iframe:"https://play.gamepix.com/tic-tac-toe-the-original-game/embed"
    },  
    {   id:47,
        imgURL:"https://skatlab.com/assets/images/games/traffic-run-online.jpg",
        ridirectURL:"https://skatlab.com/game/traffic-run-online",
        name:"Traffic Run Online",
        iframe:"https://play.gamepix.com/traffic-run-online/embed"
    },  
    {   id:48,
        imgURL:"https://skatlab.com/assets/images/games/police-traffic.jpg",
        ridirectURL:"https://skatlab.com/game/police-traffic",
        name:"Police Traffic",
        iframe:"https://play.gamepix.com/police-traffic/embed"
    },  
    {   id:49,
        imgURL:"https://skatlab.com/assets/images/games/traffic-go.jpg",
        ridirectURL:"https://skatlab.com/game/traffic-go",
        name:"Traffic Go",
        iframe:"https://play.gamepix.com/traffic-go/embed"
    },  
    {   id:50,
        imgURL:"https://skatlab.com/assets/images/games/monster-go.jpg",
        ridirectURL:"https://skatlab.com/game/monster-go",
        name:"Monster Go",
        iframe:"https://play.gamepix.com/monster-go/embed"
    },
    {   id:51,
        imgURL:"https://skatlab.com/assets/images/games/animal-skins.png",
        ridirectURL:"https://skatlab.com/game/animal-skins",
        name:"Animal Skins",
        iframe:"https://play.gamepix.com/animal-skins/embed"
    },
    {   id:52,
        imgURL:"https://skatlab.com/assets/images/games/abc-animal.jpg",
        ridirectURL:"https://skatlab.com/game/abc-animal",
        name:"ABC ANIMAL",
        iframe:"https://play.gamepix.com/abc-animal/embed"
    }, 
    {   id:53,
        imgURL:"https://skatlab.com/assets/images/games/smash-karts.jpg",
        ridirectURL:"https://skatlab.com/game/smash-karts",
        name:"Smash Karts",
        iframe:"https://play.gamepix.com/smash-karts/embed"
    },  
    {   id:54,
        imgURL:"https://skatlab.com/assets/images/games/fruit-smash-master.png",
        ridirectURL:"https://skatlab.com/game/fruit-smash-master",
        name:"Fruit Smash Master",
        iframe:"https://play.gamepix.com/fruit-smash-master/embed"
    },  
    {   id:55,
        imgURL:"https://skatlab.com/assets/images/games/trap-craft.jpg",
        ridirectURL:"https://skatlab.com/game/trap-craft",
        name:"Trap Craft",
        iframe:"https://play.gamepix.com/trap-craft/embed"
    },  
    {   id:56,
        imgURL:"https://skatlab.com/assets/images/games/pool-party.jpg",
        ridirectURL:"https://skatlab.com/game/pool-party",
        name:"Moto X3M Pool Party",
        iframe:"https://play.gamepix.com/pool-party/embed"
    },  
    {   id:57,
        imgURL:"https://skatlab.com/assets/images/games/falling-square.jpg",
        ridirectURL:"https://skatlab.com/game/falling-square",
        name:"Falling Square",
        iframe:"https://play.gamepix.com/falling-square/embed"
    },  
    {   id:58,
        imgURL:"https://skatlab.com/assets/images/games/card-battle.jpg",
        ridirectURL:"https://skatlab.com/game/card-battle",
        name:"Card Battle",
        iframe:"https://play.gamepix.com/card-battle/embed"
    },  
    {   id:59,
        imgURL:"https://skatlab.com/assets/images/games/mahjong-real.jpg",
        ridirectURL:"https://skatlab.com/game/mahjong-real",
        name:"Mahjong Real",
        iframe:"https://games.gameboss.com/mahjongreal/index.html"
    },  
]